# Algebra with numpy

In [228]:
import numpy as np
import matplotlib.pyplot as plt

In [229]:
A=[[1, 4, 6], [3, 2, 10]]
B=[[5, 3, 2], [1, 2, 7]]
C=[[0, 0, 0], [0, 0, 0]]

With simple constructs as loops

In [230]:
for r in range(len(A)):
  for c in range(len(A[0])):
    C[r][c] = A[r][c] + B[r][c]

C

[[6, 7, 8], [4, 4, 17]]

# np.array

Alternatively with numpy

In [231]:
A_= np.array(A)
B_= np.array(B)
type(A_)


numpy.ndarray

In [232]:
A_ + B_

array([[ 6,  7,  8],
       [ 4,  4, 17]])

# np.zeros, np.ones

Filling  arrays with numbers, say

- zeros

In [233]:
A42 = np.zeros((4,2))
A42

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

- ones

In [234]:
A53 = np.ones((5,3))
A53

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

- zeros (or ones) with the same shape as another existing ndarray

In [235]:
X = np.zeros_like(A53)
X

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# np.arange, np.reshape

Building an array and filling it with the values in a 1-D list

In [236]:
np.arange(3,9).reshape(3,2)

array([[3, 4],
       [5, 6],
       [7, 8]])

In [237]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


# np.linspace

Return some linearly spaced numbers

In [238]:
np.linspace(-10, 10 ,50)

array([-10.        ,  -9.59183673,  -9.18367347,  -8.7755102 ,
        -8.36734694,  -7.95918367,  -7.55102041,  -7.14285714,
        -6.73469388,  -6.32653061,  -5.91836735,  -5.51020408,
        -5.10204082,  -4.69387755,  -4.28571429,  -3.87755102,
        -3.46938776,  -3.06122449,  -2.65306122,  -2.24489796,
        -1.83673469,  -1.42857143,  -1.02040816,  -0.6122449 ,
        -0.20408163,   0.20408163,   0.6122449 ,   1.02040816,
         1.42857143,   1.83673469,   2.24489796,   2.65306122,
         3.06122449,   3.46938776,   3.87755102,   4.28571429,
         4.69387755,   5.10204082,   5.51020408,   5.91836735,
         6.32653061,   6.73469388,   7.14285714,   7.55102041,
         7.95918367,   8.36734694,   8.7755102 ,   9.18367347,
         9.59183673,  10.        ])

A less efficient but equaly exact way to do it "by hand".

In [239]:
def my_linspace(start, stop, number):
  step = (stop-start)/(number-1)
  return [ start + x * step  for x in range(number)]

In [240]:
my_linspace(-10, 10, 50)

[-10.0,
 -9.591836734693878,
 -9.183673469387756,
 -8.775510204081632,
 -8.36734693877551,
 -7.959183673469388,
 -7.551020408163265,
 -7.142857142857142,
 -6.73469387755102,
 -6.326530612244898,
 -5.918367346938775,
 -5.5102040816326525,
 -5.1020408163265305,
 -4.6938775510204085,
 -4.285714285714286,
 -3.8775510204081627,
 -3.4693877551020407,
 -3.0612244897959187,
 -2.6530612244897958,
 -2.244897959183673,
 -1.8367346938775508,
 -1.4285714285714288,
 -1.020408163265305,
 -0.612244897959183,
 -0.204081632653061,
 0.204081632653061,
 0.612244897959183,
 1.0204081632653068,
 1.4285714285714288,
 1.8367346938775508,
 2.2448979591836746,
 2.6530612244897966,
 3.0612244897959187,
 3.4693877551020407,
 3.8775510204081627,
 4.2857142857142865,
 4.6938775510204085,
 5.1020408163265305,
 5.510204081632654,
 5.918367346938776,
 6.326530612244898,
 6.73469387755102,
 7.142857142857142,
 7.551020408163264,
 7.95918367346939,
 8.367346938775512,
 8.775510204081634,
 9.183673469387756,
 9.591836734

# np.random

In [241]:
np.random.normal(100,2,size=15)

array([ 99.50641377,  96.0184011 , 100.66409825, 101.20402982,
       101.02709031, 101.64531738, 100.53008025, 100.15635015,
       102.38599419,  99.54881493, 100.11136513,  99.49365915,
        99.82605704, 101.13855819,  98.77368659])

## some distributions

## Normal

In [248]:
X=np.random.normal(10,2,21).reshape(7,3)
print(X)
print(np.mean(X))
print(np.std(X))

[[11.06036947 15.16123812 11.49540504]
 [ 9.6821476  10.46115927  7.60167452]
 [ 8.84995926  9.54321211 10.41046787]
 [10.86848371 11.01016576  7.20817083]
 [10.3725837   8.76869122 12.13252802]
 [ 7.64032073 11.61998647 10.5571171 ]
 [12.67557356 10.80523579  8.17632354]]
10.29051493652197
1.843900600102521


# Uniform

In [253]:
X=np.random.uniform(1,10,20)
print(X)
print(np.mean(X))
print(np.std(X))

[5.68328107 2.44781495 5.07034568 1.97477459 8.40695649 9.23679067
 2.14643291 4.37223528 8.25429398 1.95993618 7.34880595 6.62683744
 1.86098147 5.46769591 2.6456195  3.12027433 6.2117987  4.16367809
 6.17489874 1.89027104]
4.753186148791469
2.3809352159550556


Some functions apply to some dimension (axis) of the matrix

In [249]:
A=np.array([[2, 4], [9, 3]])
A

array([[2, 4],
       [9, 3]])

In [ ]:
A.sum(0)

array([11,  7])

In [ ]:
A.sum(1)

array([ 6, 12])

In [ ]:
A.sum((0, 1))

np.int64(18)

In [ ]:
A=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
A

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
A.sum(0)

array([[ 6,  8],
       [10, 12]])

In [ ]:
A.sum(2)

array([[ 3,  7],
       [11, 15]])

# Broadcasting


In [302]:
A=np.arange(27).reshape(3,3,3)
B=np.arange(3).reshape(3,1)
A+B
(A+B).shape

(3, 3, 3)

In [281]:
12//10

1

# np.argsort

In [314]:
# 2D array
arr = np.array([[10, 3, 5],
                [1, 8, 2]])

# Flattened index of the 3 smallest elements
flat_indices = np.argsort(arr, axis=None)[:3]

# Convert to 2D positions
positions = np.unravel_index(flat_indices, arr.shape)

# Display results
print("Flat indices:", flat_indices)
print("2D positions:", positions)
print("Values:", arr[positions])


Flat indices: [3 5 1]
2D positions: (array([1, 1, 0]), array([0, 2, 1]))
Values: [1 2 3]


# my_argsort

In [327]:
L=[1,3,4,8,9,5,2,7]
LS=sorted(L)
print(L)
[L[y] for y in ([L.index(x) for x in LS] [:3])]

[1, 3, 4, 8, 9, 5, 2, 7]


[1, 2, 3]

# Adding axis

In [328]:
D=np.array([1,3,7,5])

In [329]:
D.shape

(4,)

In [332]:
D[:,np.newaxis]

array([[1],
       [3],
       [7],
       [5]])

In [333]:
D[np.newaxis,:]

array([[1, 3, 7, 5]])

In [331]:
D[:,np.newaxis] - D[np.newaxis,:]

array([[ 0, -2, -6, -4],
       [ 2,  0, -4, -2],
       [ 6,  4,  0,  2],
       [ 4,  2, -2,  0]])